import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { jsPDF } from "jspdf";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export async function GET(req: NextRequest) {
  try {
    // Get the access token from cookies
    const accessToken = req.cookies.get("sb-auth-token")?.value;

    if (!accessToken) {
      return NextResponse.json(
        { success: false, error: "Not authenticated" },
        { status: 401 }
      );
    }

    // Get enrollment ID from query params
    const searchParams = req.nextUrl.searchParams;
    const enrollmentId = searchParams.get("enrollmentId");

    if (!enrollmentId) {
      return NextResponse.json(
        { success: false, error: "Enrollment ID is required" },
        { status: 400 }
      );
    }

    // Create a Supabase client with the access token
    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      },
    });

    // Get the user from Supabase Auth
    const { data: { user }, error: authError } = await supabase.auth.getUser(accessToken);

    if (authError || !user) {
      return NextResponse.json(
        { success: false, error: "Authentication failed" },
        { status: 401 }
      );
    }

    // Fetch enrollment with user, program, and student_id
    const { data: enrollment, error: enrollmentError } = await supabase
      .from("training_enrollments")
      .select(`
        *,
        training_programs (
          name,
          start_date,
          end_date
        )
      `)
      .eq("id", enrollmentId)
      .eq("user_id", user.id)
      .single();

    if (enrollmentError || !enrollment) {
      return NextResponse.json(
        { success: false, error: "Enrollment not found" },
        { status: 404 }
      );
    }

    // Fetch user details for name
    const { data: userData } = await supabase
      .from("users")
      .select("full_name, email")
      .eq("id", user.id)
      .single();

    if (enrollmentError || !enrollment) {
      return NextResponse.json(
        { success: false, error: "Enrollment not found" },
        { status: 404 }
      );
    }

    // Check if deposit is paid (required for ID card)
    if (enrollment.enrollment_status !== "deposit_paid" && enrollment.enrollment_status !== "fully_paid") {
      return NextResponse.json(
        { success: false, error: "ID card is only available after deposit payment" },
        { status: 400 }
      );
    }

    // Student ID should be auto-generated when deposit is paid, but generate it if missing
    let studentId = enrollment.student_id;
    if (!studentId && enrollment.deposit_paid_at) {
      // Generate student ID on the fly if it wasn't generated by trigger
      const depositDate = new Date(enrollment.deposit_paid_at);
      const quarter = Math.floor(depositDate.getMonth() / 3) + 1;
      const year = depositDate.getFullYear();

      // Count existing enrollments in this quarter/year (excluding current one)
      const { count } = await supabase
        .from("training_enrollments")
        .select("*", { count: "exact", head: true })
        .eq("enrollment_status", "deposit_paid")
        .neq("id", enrollment.id)
        .lte("deposit_paid_at", enrollment.deposit_paid_at);

      const paymentOrder = (count || 0) + 1;
      studentId = `${String(paymentOrder).padStart(3, "0")}/Q${quarter}/${year}`;

      // Save student ID to database
      await supabase
        .from("training_enrollments")
        .update({ student_id: studentId })
        .eq("id", enrollmentId);
    } else if (!studentId) {
      return NextResponse.json(
        { success: false, error: "Student ID cannot be generated. Deposit payment date is missing." },
        { status: 400 }
      );
    }

    const studentName = userData?.full_name || "Student";
    const programName = enrollment.training_programs?.name || "Pharma Sales Training";
    
    // Calculate validity (1 month from deposit payment date)
    const depositDate = new Date(enrollment.deposit_paid_at || enrollment.created_at);
    const validUntil = new Date(depositDate);
    validUntil.setMonth(validUntil.getMonth() + 1);

    // Generate ID Card PDF
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: [85.6, 53.98], // Standard ID card size (credit card size)
    });

    // Set colors - matching medical badge style
    const lightBlue = [173, 216, 230]; // Light blue accents
    const darkBlue = [41, 70, 114]; // Dark blue for text
    const red = [220, 20, 60]; // Red for expiration date

    // White background
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, 85.6, 53.98, "F");

    // Light blue triangular accent on bottom left corner
    doc.setFillColor(lightBlue[0], lightBlue[1], lightBlue[2]);
    // Draw triangle by creating small rectangles in a triangular pattern
    const triangleSize = 14;
    for (let row = 0; row < triangleSize; row++) {
      const width = row + 1;
      const yPos = 53.98 - (row + 1);
      doc.rect(0, yPos, width, 1, "F");
    }

    // Light blue rectangular section on right side (subtle, no text)
    doc.setFillColor(lightBlue[0], lightBlue[1], lightBlue[2]);
    doc.rect(60, 0, 25.6, 53.98, "F");

    // Center alignment for main content area (left side, avoiding the light blue section)
    const contentWidth = 57; // Width of content area
    const centerX = 3 + contentWidth / 2; // Center point of content area

    // Use Helvetica font (cleaner, more professional)
    doc.setFont("helvetica");

    // Company name at top (centered, two lines) - Larger and with padding
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const companyName1 = "PECKERS";
    const companyName2 = "SWIFTSERVE LTD";
    doc.text(companyName1, centerX, 6, { align: "center" });
    doc.text(companyName2, centerX, 9.5, { align: "center" });

    // Medical/training icon/symbol centered below company name with good padding
    doc.setFillColor(darkBlue[0], darkBlue[1], darkBlue[2]);
    doc.setDrawColor(darkBlue[0], darkBlue[1], darkBlue[2]);
    doc.setLineWidth(0.6);
    // Draw cross centered with better spacing
    doc.rect(centerX - 1.5, 13, 3, 11, "F"); // Vertical line (centered, thicker)
    doc.rect(centerX - 5, 17, 10, 3, "F"); // Horizontal line (centered, thicker)

    // Student Name - prominently displayed, centered (bold, larger) with padding
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    const nameLines = doc.splitTextToSize(studentName, contentWidth - 4);
    doc.text(nameLines, centerX, 28, { align: "center" });

    // Course/Program name (italicized, larger, centered) with padding
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    const courseLines = doc.splitTextToSize(programName.toUpperCase(), contentWidth - 4);
    doc.text(courseLines, centerX, 34.5, { align: "center" });

    // Student ID (centered, larger) with more padding from course name
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.text("ID # " + studentId, centerX, 41.5, { align: "center" });

    // Valid through date (in red, larger, centered) with padding
    doc.setTextColor(red[0], red[1], red[2]);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    const validDateText = `Valid through ${validUntil.toLocaleDateString("en-US", {
      month: "2-digit",
      day: "2-digit",
      year: "2-digit",
    })}`;
    doc.text(validDateText, centerX, 46.5, { align: "center" });

    // Subtle border
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.rect(0.5, 0.5, 84.6, 52.98, "S");

    // Generate PDF blob
    const pdfBlob = doc.output("blob");

    // Return as PDF
    return new NextResponse(pdfBlob, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Peckers-ID-${studentId || enrollmentId}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error("Error generating ID card:", error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}

